spring.application.name=user-service
server.port=8081

spring.mongodb.uri=mongodb+srv://vietthanh0135_db_user:Tony0387530876@cluster0.lszlvb9.mongodb.net/user_service_db?retryWrites=true&w=majority&appName=Cluster0
app.jwt.secret=${JWT_SECRET:bXktdmVyeS1zZWNyZXQtYW5kLWxvbmcta2V5LTEyMzQ1Ng==}
app.jwt.expiration=86400000


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.mongodb.enabled=false