spring.application.name=product-service

# Cổng chạy của product-service (khác với user-service 8080)
server.port=8081

# Kết nối tới MongoDB Atlas
spring.mongodb.uri=mongodb+srv://vietthanh0135_db_user:Tony0387530876@cluster0.va5s08w.mongodb.net/product_db?retryWrites=true&w=majority
